### ISSUE TITLE
Why does package.json not point to the latest clang_revision?

### ISSUE THREAD

**Issue by jmillan** [hokein/clang-tools-prebuilt#3]
Hi @hokein,

This is not an issue but a mere question. I see that there is a newer prebuilt clang-tools [release](https://github.com/hokein/clang-tools-tarball/releases/tag/r298696) than the one pointed by the package.json file `275826`.

Is there any special reason for that? I would expect the npm to install the latest one.

Kind regards.

**Comment by hokein** [comment]
Because the latest `clang-tools-tarball` is missing the linux binaries, I will upload the linux binaries and bump `clang-tools-prebuilt`.

**Comment by jmillan** [comment]
Nice, thanks!

**Comment by hokein** [comment]
Have bumped v0.1.3.

**Comment by ibc** [comment]
Thanks a lot.
